### ISSUE TITLE
Unhandled Exception getting GPU Stats 

### ISSUE THREAD

**Issue by GabrielFernandes-Dev** [microsoft/devhome#1117]
### Dev Home version

0.1.3651.0

### Windows build number

10.0.22000

### Steps to reproduce the bug

Installed the Dev Home app but the pc widgets never worked (CPU, GPU, Memory, and Network). 

Cloning the project and trying to run whit Visual Studio Community 2022 the application starts and immediately throws an
exception 

### Actual result

**This is the DevHome app widgets.**
 
![image](https://github.com/microsoft/devhome/assets/79493036/a8e877ab-0e47-4f38-b78d-3d586e39550c)

Running whit Visual Studio Community get this exception in the \devhome\CoreWidgetProvider\Helpers\SystemData.cs Line 12.

System.TypeInitializationException: 'The type initializer for 'CoreWidgetProvider.Helpers.SystemData' threw an exception.'
Inner Exception
InvalidOperationException: Cannot load Counter Name data because an invalid index '' was read from the registry. Performance counters on the machine may need to be repaired.

![image](https://github.com/microsoft/devhome/assets/79493036/cd3daecd-baf4-4265-a507-9a2dd5e4b7ac)

### Included System Information

I am currently with this configuration in my PC:
Ryzen 5 3600
ASRock B450M
32 Gb DDR4 
RTX 3060Ti

**Comment by krschau** [comment]
@gabrielgomes-coder When you ran locally, did you have this change in your branch?
https://github.com/microsoft/devhome/pull/1077

**Comment by wsy** [comment]
![image](https://github.com/microsoft/devhome/assets/2684991/018c3c6c-badf-4911-ae67-3b8952bf6921)
Hi @krschau ,
This bug still exists in version '0.1201.442.0'.
All widgets have this issue.

**Comment by LambdaSoft** [comment]
Today I updated through the Microsoft Store (0.1501.533.0) and, at least in my case, it was finally fixed

**Comment by duxingzhe** [comment]
It is still not working for me.

**Comment by BigWull** [comment]
Still not working

**Comment by Serios** [comment]
I can confirm that all the widgets regarding system performance are still throwing this error.

**Comment by pkeuter** [comment]
It seems that the performance counters can not be found:

```
[2024/11/25 09:24:03.211 ERR] (SystemCPUUsageWidget/4df6da) Error retrieving stats.
System.TypeInitializationException: The type initializer for 'CoreWidgetProvider.Helpers.SystemData' threw an exception.
 ---> System.InvalidOperationException: Could not locate Performance Counter with specified category name 'Memory', counter name 'Cache Bytes'.
   at System.Diagnostics.PerformanceCounter.InitializeImpl()
   at System.Diagnostics.PerformanceCounter..ctor(String categoryName, String counterName, String instanceName, Boolean readOnly)
   at CoreWidgetProvider.Helpers.MemoryStats..ctor()
   at CoreWidgetProvider.Helpers.SystemData..cctor()
   --- End of inner exception stack trace ---
   at CoreWidgetProvider.Helpers.DataManager.GetCPUStats()
   at CoreWidgetProvider.Widgets.SystemCPUUsageWidget.LoadContentData()
```
But the performance counter does exist when looking in the Performance Monitor though:
![Image](https://github.com/user-attachments/assets/f65604de-30aa-42ba-b25b-1eea187690fb)


This was tested with version `0.1901.687.0`
