### ISSUE TITLE
I don't see any applications

### ISSUE THREAD

**Issue by skanda890** [microsoft/devhome#1645]
### Dev Home version

0.503.261.0

### Windows build number

10.0.22621.2361

### Other software

OS Build Version: 10.0.22621.2361.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.21

### Steps to reproduce the bug

I don't see any applications in the Machine configuration> End-to-End setup or go to Machine configuration>Install applications

### Expected result

I should have seen some applications 

### Actual result

It didn't show any applications

### Included System Information

Physical Memory: 11.89GB (4.22GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.503.261.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.501.261.0_x64__8wekyb3d8bbwe

**Comment by skanda890** [comment]
But I have the Extension installed on my computer.

**Comment by AmelBawa-msft** [comment]
@skanda890, is this issue possibly related to this?
#1596

**Comment by skanda890** [comment]
Yes It is related.

**Comment by skanda890** [comment]
Yes It is related.

**Comment by StefaniaCastelli** [comment]
So, if you can't unlock the firewall process from its hanging status, I cannot see other alternatives than the restore one.
Before doing it, I would check Feedback Hub instead of GitHub (I didn't do it) to see Firewall and Store related issues with the error codes or other key words (maybe someone found an easier solution).
And if the restore (or fresh restart) keeping your file is the only option you have, save on OneDrive or elsewhere what's not already in the cloud.
Let me know how it goes, if you like.

Good Luck
________________________________

**Comment by AmelBawa-msft** [comment]
@skanda890, can you please check which version of winget is installed on your machine?
```
winget -v
```
and possibly try to search for a package to see if you get any errors:
```
 winget search Microsoft.VisualStudioCode
```

**Comment by skanda890** [comment]
It was in the version 'v1.6.2771'.It gave me an error called "Failed in attempting to update the source: winget
Failed when searching source; results will not be included: winget
No package found matching input criteria.".

**Comment by skanda890** [comment]
I couldn't update it. How do I update it? I've tried everything.

**Comment by AmelBawa-msft** [comment]
@skanda890, sorry for the delay. Can you please try updating App Installer from the store and try again?

Steps:
- Close Dev Home (to terminate the WinGet COM server which can block the update)
- Update AppInstaller from the store: `ms-windows-store://pdp/?productid=9NBLGGH4NNS1`
- Re-open Dev Home and retry the same flow to validate that the apps are showing

**Comment by skanda890** [comment]
The Microsoft Store didn't give the option to update

**Comment by skanda890** [comment]
I completed the first step, but the second one that @AmelBawa-msft gave me I couldn't finish.

**Comment by skanda890** [comment]
In Microsoft Store, if I try to download any apps, it would give an error in the library saying "Something happened on our end." or if you check in that specific app page you will see an error called "There is a problem." and Code:'0x8015DC12'.

**Comment by AmelBawa-msft** [comment]
@skanda890 can you try updating it manually (powershell) from https://github.com/microsoft/winget-cli/releases to see if that bypasses the store error?

```ps
Add-AppPackage Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle -ForceUpdateFromAnyVersion -ForceApplicationShutdown
```

CC: @denelon

**Comment by skanda890** [comment]
If you can record the steps on how to do that, it would be helpful.

**Comment by skanda890** [comment]
Can you contact me in Quick Assist?

**Comment by skanda890** [comment]
How do I run this?

**Comment by skanda890** [comment]
When I tried it gave me this issue "Add-AppPackage : Cannot find path 'C:\Users\Skand_zncmqfh\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle' because it does not exist.
At line:1 char:1
+ Add-AppPackage Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\Skand_...bbwe.msixbundle:String) [Add-AppxPackage], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand"

**Comment by skanda890** [comment]
Or, is there any other method?

**Comment by AmelBawa-msft** [comment]
@skanda890, `Add-AppxPackage` requires the package to be available on your local disk. To do that:
1. Go to: https://github.com/microsoft/winget-cli/releases/tag/v1.7.2782-preview
2. Download the msixbundle from the assets and save it on your machine:
<img src="https://github.com/microsoft/devhome/assets/104940545/84f87326-3533-4e5d-ac87-a6df1e3db515" Width="300" />

3. From powershell, enter the following command:
```
cd "<folder where the msixbundle was downloaded>"
```
then, attempt to update the package manually by typing: 
```
Add-AppPackage Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle -ForceUpdateFromAnyVersion -ForceApplicationShutdown
```

**Comment by skanda890** [comment]
Thanks, I will try that.

**Comment by skanda890** [comment]
> @skanda890, sorry for the delay. Can you please try updating App Installer from the store and try again?
> 
> Steps:
> 
> * Close Dev Home (to terminate the WinGet COM server which can block the update)
> * Update AppInstaller from the store: `ms-windows-store://pdp/?productid=9NBLGGH4NNS1`
> * Re-open Dev Home and retry the same flow to validate that the apps are showing

I have finished these steps, but still doesn't work.

**Comment by AmelBawa-msft** [comment]
@denelon, have you see this issue before? I suspect Dev Home is unable to show the apps because AppInstaller/Winget is erroring.

**Comment by skanda890** [comment]
Yeah, the Microsoft Store isn't working so probably all Microsoft Store packages won't work.

**Comment by skanda890** [comment]
Yeah, the Microsoft Store isn't working sometimes, probably this may be the issue.

**Comment by denelon** [comment]
I don't believe I've ever seen this issue before.

**Comment by skanda890** [comment]
Yeah, I've never had this kind of big in any other Winget/App Installer related application.

**Comment by skanda890** [comment]
I got a picture.
![Uploading image.png…]()

**Comment by AmelBawa-msft** [comment]
> the Microsoft Store and Winget/App Installer are giving errors while trying to install the applications. Is this the cause of this issue?

That's likely the reason. Dev Home communicates with WinGet to search/install packages on the machine. From the screenshot you posted, I can tell that the connection to WinGet failed because the search box is disabled.

To better troubleshoot the issue, is it possible to inspect Dev Home logs at:
```
%LOCALAPPDATA%\Packages\Microsoft.Windows.DevHome_8wekyb3d8bbwe\TempState\SetupFlow
```

And winget logs at:
```
%LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir
```

for any possible error reasons?

**Comment by skanda890** [comment]
> * 9NBLGGH4NNS1

I tried another way but it failed.

**Comment by JoanComasFdz** [comment]
I have the same issue:

Dev Home version
0.901.374.0

Windows build number
Windwos 11 Version 22h2 (OS Build 22621.2861)

Other software
.NET Version:  8.0.100
AppInstaller version: 1.21.3482.0
Winget version: v1.6.3482

Steps to reproduce the bug

1. Open DevHome
2. Go to Machine configuration
3. Click on end-to-end setup
4. Click next (or configure a repo, it doesn't matter)
5. Search for "GitHub" (or anything)

No applications are shown.

Expected result
I should have seen some applications

Actual result
It didn't show any applications

Included System Information
Physical Memory: 64GB (20GB used)
Processor Architecture: x64

Included Extensions Information
Extensions:
Azure Extension v 0.400.374.0
GitHub Extension v 0.900.374.0
WingetUI v 0.3.0.0

The DevHome Logs show the following error:

```
[2024-01-16 12:45:08.9260][AppManagement] INFO: Searching for 'GitHub' on catalog . Result limit: 20
[2024-01-16 12:45:08.9309][AppManagement] INFO: Performing search
[2024-01-16 12:45:09.0285][AppManagement] INFO: Found System.Collections.Generic.IReadOnlyListImpl`1[Microsoft.Management.Deployment.MatchResult] results
[2024-01-16 12:45:09.0293][AppManagement] INFO: Found [GitHub.cli]
[2024-01-16 12:45:09.0310][AppManagement] INFO: Found [zhaopengme.gitnote]
[2024-01-16 12:45:09.0321][AppManagement] INFO: Found [StefHeyenrath.GitHubReleaseNotes]
[2024-01-16 12:45:09.0332][AppManagement] INFO: Found [PenguinLabs.Cacher]
[2024-01-16 12:45:09.0344][AppManagement] INFO: Found [nektos.act]
[2024-01-16 12:45:09.0355][AppManagement] INFO: Found [Microsoft.AppInstallerFileBuilder]
[2024-01-16 12:45:09.0365][AppManagement] INFO: Found [manosim.gitify]
[2024-01-16 12:45:09.0377][AppManagement] INFO: Found [GitHub.GitLFS]
[2024-01-16 12:45:09.0391][AppManagement] INFO: Found [GitHub.GitHubDesktop.Beta]
[2024-01-16 12:45:09.0401][AppManagement] INFO: Found [dvcrn.markright]
[2024-01-16 12:45:09.0411][AppManagement] INFO: Found [docmirror.dev-sidecar]
[2024-01-16 12:45:09.0422][AppManagement] INFO: Found [CosmoX.Lepton]
[2024-01-16 12:45:09.0433][AppManagement] INFO: Found [CoolPlayLin.FastGithub]
[2024-01-16 12:45:09.0443][AppManagement] INFO: Found [LeGitHubDeTai.AnimeBack]
[2024-01-16 12:45:09.0454][AppManagement] INFO: Found [GitHub.GitHubDesktop]
[2024-01-16 12:45:09.0465][AppManagement] INFO: Found [GitHub.ClassroomAssistant]
[2024-01-16 12:45:09.0476][AppManagement] INFO: Found [GitHub.Atom.Beta]
[2024-01-16 12:45:09.0487][AppManagement] INFO: Found [GitHub.Atom]
[2024-01-16 12:45:09.0499][AppManagement] INFO: Found [GitHub.hub]
[2024-01-16 12:45:09.0509][AppManagement] INFO: Found [Vipre.IPVTest]
[2024-01-16 12:45:09.0740][AppManagement] ERROR: Search error.
System.Runtime.InteropServices.COMException (0x8A15003A)
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Microsoft.Management.Deployment.IPackageManagerMethods.GetPredefinedPackageCatalog(IObjectReference _obj, PredefinedPackageCatalog predefinedPackageCatalog)
   at DevHome.SetupFlow.Services.WindowsPackageManager.GetPredefinedCatalogId(PredefinedPackageCatalog catalog)
   at DevHome.SetupFlow.Services.WindowsPackageManager.<.ctor>b__12_1()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location ---
   at System.Lazy`1.CreateValue()
   at DevHome.SetupFlow.Services.WindowsPackageManager.get_MsStoreId()
   at DevHome.SetupFlow.ViewModels.PackageViewModel.GetPackageDescription()
   at DevHome.SetupFlow.ViewModels.PackageViewModel..ctor(ISetupFlowStringResource stringResource, IWindowsPackageManager wpm, IWinGetPackage package, IThemeSelectorService themeSelector, IScreenReaderService screenReaderService, WindowsPackageManagerFactory wingetFactory, IHost host)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance[T](IServiceProvider provider, Object[] parameters)
   at DevHome.SetupFlow.Extensions.ServiceExtensions.<>c__DisplayClass1_0.<AddAppManagement>b__4(IWinGetPackage package)
   at DevHome.SetupFlow.Services.PackageProvider.CreateOrGet(IWinGetPackage package, Boolean cachePermanently)
   at DevHome.SetupFlow.ViewModels.SearchViewModel.<>c__DisplayClass13_0.<SearchAsync>b__2(IWinGetPackage m)
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at DevHome.SetupFlow.ViewModels.SearchViewModel.<>c__DisplayClass13_1.<SearchAsync>b__1()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at DevHome.SetupFlow.ViewModels.SearchViewModel.SearchAsync(String text, CancellationToken cancellationToken)
[2024-01-16 12:45:09.0747][AppManagement] ERROR: Search failed with status: ExceptionThrown
[2024-01-16 12:45:09.0843][AppManagement] ERROR: Search error.
System.Runtime.InteropServices.COMException (0x8A15003A)
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Microsoft.Management.Deployment.IPackageManagerMethods.GetPredefinedPackageCatalog(IObjectReference _obj, PredefinedPackageCatalog predefinedPackageCatalog)
   at DevHome.SetupFlow.Services.WindowsPackageManager.GetPredefinedCatalogId(PredefinedPackageCatalog catalog)
   at DevHome.SetupFlow.Services.WindowsPackageManager.<.ctor>b__12_1()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location ---
   at System.Lazy`1.CreateValue()
   at DevHome.SetupFlow.Services.WindowsPackageManager.get_MsStoreId()
   at DevHome.SetupFlow.ViewModels.PackageViewModel.GetPackageDescription()
   at DevHome.SetupFlow.ViewModels.PackageViewModel..ctor(ISetupFlowStringResource stringResource, IWindowsPackageManager wpm, IWinGetPackage package, IThemeSelectorService themeSelector, IScreenReaderService screenReaderService, WindowsPackageManagerFactory wingetFactory, IHost host)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance[T](IServiceProvider provider, Object[] parameters)
   at DevHome.SetupFlow.Extensions.ServiceExtensions.<>c__DisplayClass1_0.<AddAppManagement>b__4(IWinGetPackage package)
   at DevHome.SetupFlow.Services.PackageProvider.CreateOrGet(IWinGetPackage package, Boolean cachePermanently)
   at DevHome.SetupFlow.ViewModels.SearchViewModel.<>c__DisplayClass13_0.<SearchAsync>b__2(IWinGetPackage m)
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at DevHome.SetupFlow.ViewModels.SearchViewModel.<>c__DisplayClass13_1.<SearchAsync>b__1()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at DevHome.SetupFlow.ViewModels.SearchViewModel.SearchAsync(String text, CancellationToken cancellationToken)
[2024-01-16 12:45:09.0846][AppManagement] ERROR: Search failed with status: ExceptionThrown
```

I have retarted the PC and it still does not work.

Any ideas?

**Comment by skanda890** [comment]
Fixed! I checked in the latest version.

**Comment by skanda890** [comment]
Change the label to 'Resolution-Fixed'.
