### ISSUE TITLE
Extension not found when trying to sign-in

### ISSUE THREAD

**Issue by skanda890** [microsoft/devhome#1729]
### Dev Home version

0.601.285.0

### Windows build number

10.0.22621.2428

### Other software

OS Build Version: 10.0.22621.2428.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.22

### Steps to reproduce the bug

Go to Settings>Accounts>Add Account. I have an extension that requires an account.

### Expected result

It should let us add our account because we have an extension that requires an account.

### Actual result

It said there were no extensions that required an account.

### Included System Information

Physical Memory: 11.89GB (1.61GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHomeGitHubExtension_0.600.283.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHome_0.601.285.0_x64__8wekyb3d8bbwe

**Comment by skanda890** [comment]
Can you make it so that anybody can link their account, without having an extension that requires an account?

**Comment by skanda890** [comment]
It says "No extensions found
             Install a Dev Home extension that uses your developer account, then sign in to add the account.

**Comment by krschau** [comment]
I'm sorry, I misunderstood the original question.

Did you disable the extension before trying to log in with it? Disabling the extension would cause Dev Home to act like no extension is installed and show that message.

**Comment by skanda890** [comment]
No, I didn't disable the extension.

**Comment by krschau** [comment]
@vineeththomasalex Can you take this?

**Comment by skanda890** [comment]
TheLogs:https://1drv.ms/f/s!Aqq-Je19xlrfhGdaqODLtf4LHSxB?e=BTycUZ

**Comment by vineeththomasalex** [comment]
[2023-10-19 04:46:17.4796][DevHome] ERROR: Failed to get IDeveloperIdProvider provider from 'Dev Home GitHub Extension (Preview)'
System.ArgumentNullException: Value cannot be null. (Parameter 'o')
   at System.Runtime.InteropServices.Marshal.GetIUnknownForObject(Object o)
   at DevHome.Models.ExtensionWrapper.<StartExtensionAsync>b__31_0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at DevHome.Models.ExtensionWrapper.StartExtensionAsync()
   at DevHome.Models.ExtensionWrapper.GetProviderAsync[T]()
   at DevHome.Services.AccountsService.GetDevIdProviders()
   
   
This is very likely a symptom of the Extension crashing.

**Comment by skanda890** [comment]
So, how do I fix this?

**Comment by skanda890** [comment]
In the new build #1945 happens.

**Comment by vineeththomasalex** [comment]
Duplicating to #1945

**Comment by skanda890** [comment]
Not duplicate. That happens in the new build and this doesn't.
