### ISSUE TITLE
Permissions Issues With Docker Compose File With Attached Volumes From A Dev Drive Volume

### ISSUE THREAD

**Issue by GingerGraham** [microsoft/devhome#1805]
### Dev Home version

0.601.297.0

### Windows build number

10.0.25982.1000

### Other software

OS Build Version: 10.0.25982.1000.amd64fre.rs_prerelease.231020-1353
.NET Version: .NET 6.0.23

### Steps to reproduce the bug

Using a Jekyll website with the jekyll/jekyll:stable or latest container image and mounting a local directory for /srv into the container when running jekyll serve the container errors and exits with a Operation not permitted @ apply2files error (Errno: EPERM)

### Expected result

Jekyll launches and runs normally

### Actual result

2023-11-01 16:47:59

docker-grahamwattsweb-1
[31m ------------------------------------------------[0m

2023-11-01 16:47:59

docker-grahamwattsweb-1
[31m Jekyll 4.3.2 Please append `--trace` to the `serve` command [0m

2023-11-01 16:47:59

docker-grahamwattsweb-1
[31m for any additional information or backtrace. [0m

2023-11-01 16:47:59

docker-grahamwattsweb-1
[31m ------------------------------------------------[0m

2023-11-01 16:47:59

docker-grahamwattsweb-1
/usr/gem/gems/jekyll-4.3.2/lib/jekyll/static_file.rb:201:in `utime': Operation not permitted @ apply2files - /srv/jekyll/_site/69dbd32e0e414e4fbf22acef967a9228.txt (Errno::EPERM)

2023-11-01 16:47:59

docker-grahamwattsweb-1
from /usr/gem/gems/jekyll-4.3.2/lib/jekyll/static_file.rb:201:in `copy_file'

2023-11-01 16:47:59

docker-grahamwattsweb-1
from /usr/gem/gems/jekyll-4.3.2/lib/jekyll/static_file.rb:107:in `write'

2023-11-01 16:47:59

docker-grahamwattsweb-1
from /usr/gem/gems/jekyll-4.3.2/lib/jekyll/site.rb:231:in `block in write'

2023-11-01 16:47:59

docker-grahamwattsweb-1
from /usr/gem/gems/jekyll-4.3.2/lib/jekyll/site.rb:364:in `block in each_site_file'

2023-11-01 16:47:59

docker-grahamwattsweb-1
from /usr/gem/gems/jekyll-4.3.2/lib/jekyll/site.rb:364:in `each'

2023-11-01 16:47:59

docker-grahamwattsweb-1
from /usr/gem/gems/jekyll-4.3.2/lib/jekyll/site.rb:364:in `each_site_file'

2023-11-01 16:47:59

docker-grahamwattsweb-1
from /usr/gem/gems/jekyll-4.3.2/lib/jekyll/site.rb:230:in `write'

2023-11-01 16:47:59

docker-grahamwattsweb-1
from /usr/gem/gems/jekyll-4.3.2/lib/jekyll/site.rb:82:in `process'

2023-11-01 16:47:59

docker-grahamwattsweb-1
from /usr/gem/gems/jekyll-4.3.2/lib/jekyll/command.rb:28:in `process_site'

2023-11-01 16:47:59

docker-grahamwattsweb-1
from /usr/gem/gems/jekyll-4.3.2/lib/jekyll/commands/build.rb:65:in `build'

2023-11-01 16:47:59

docker-grahamwattsweb-1
from /usr/gem/gems/jekyll-4.3.2/lib/jekyll/commands/build.rb:36:in `process'

2023-11-01 16:47:59

docker-grahamwattsweb-1
from /usr/gem/gems/jekyll-4.3.2/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'

2023-11-01 16:47:59

docker-grahamwattsweb-1
from /usr/gem/gems/jekyll-4.3.2/lib/jekyll/command.rb:91:in `each'

2023-11-01 16:47:59

docker-grahamwattsweb-1
from /usr/gem/gems/jekyll-4.3.2/lib/jekyll/command.rb:91:in `process_with_graceful_fail'

2023-11-01 16:47:59

docker-grahamwattsweb-1
from /usr/gem/gems/jekyll-4.3.2/lib/jekyll/commands/serve.rb:86:in `block (2 levels) in init_with_program'

2023-11-01 16:47:59

docker-grahamwattsweb-1
from /usr/gem/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'

2023-11-01 16:47:59

docker-grahamwattsweb-1
from /usr/gem/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'

2023-11-01 16:47:59

docker-grahamwattsweb-1
from /usr/gem/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'

2023-11-01 16:47:59

docker-grahamwattsweb-1
from /usr/gem/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'

2023-11-01 16:47:59

docker-grahamwattsweb-1
from /usr/gem/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'

2023-11-01 16:47:59

docker-grahamwattsweb-1
from /usr/gem/gems/jekyll-4.3.2/exe/jekyll:15:in `<top (required)>'

2023-11-01 16:47:59

docker-grahamwattsweb-1
from /usr/local/bundle/bin/jekyll:27:in `load'

2023-11-01 16:47:59

docker-grahamwattsweb-1
from /usr/local/bundle/bin/jekyll:27:in `<main>'

However running the same docker compose from the same repo cloned locally to a non-Dev Drive launches normally.  The issue only presents on a Dev Drive

### Included System Information

Physical Memory: 31.73GB (13.14GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.601.297.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.600.283.0_x64__8wekyb3d8bbwe

**Comment by nesherhh** [comment]
Have same issue with PostgreSQL.
```
chmod: changing permissions of '/var/lib/postgresql/data': Operation not permitted
initdb: error: could not change permissions of directory "/var/lib/postgresql/data": Operation not permitted
```
https://github.com/docker/for-win/issues/13613
https://github.com/docker/for-win/issues/13877

**Comment by AdamBraden** [comment]
Likely a dupe of 
https://github.com/microsoft/WSL/issues/10792
