### ISSUE TITLE
Dev Home (Preview) - No found login to GitHub Account

### ISSUE THREAD

**Issue by GeboArt** [microsoft/devhome#2126]
### Dev Home version

0.801.344.0

### Windows build number

10.0.22635.2921

### Other software

OS Build Version: 10.0.22635.2921.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.25

### Steps to reproduce the bug

In Settings > Accounts, I click on add account and in the pop-up window I press the "Sign in to github.com" button but it does not open any browser window or any login form to log in so it is not possible to add an account .

### Actual result

no login found.

### Included System Information

CPU: AMD Ryzen 7 4800H with Radeon Graphics         
Physical Memory: 15.37GB (4.53GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.801.344.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.900.374.0_x64__8wekyb3d8bbwe

**Comment by shreerajshrestha** [comment]
Root Cause: 
`[2024/05/25 20:55:17.278 ERR] (DevBoxManagementService) DevBoxHttpRequest failed: Exception
System.Net.Http.HttpRequestException: DevBoxHttpRequest failed: Unauthorized {"error":{"code":"AuthenticationFailedMissingToken","message":"Authentication failed. The 'Authorization' header is missing the access token."}}
   at AzureExtension.Services.DevBox.DevBoxManagementService.DevBoxHttpRequest(HttpClient client, Uri webUri, IDeveloperId developerId, HttpMethod method, HttpContent requestContent)
[2024/05/25 20:55:17.349 ERR] (DevBoxProvider) Unable to get the adaptive card session for the provided developerId
System.Net.Http.HttpRequestException: DevBoxHttpRequest failed: Unauthorized {"error":{"code":"AuthenticationFailedMissingToken","message":"Authentication failed. The 'Authorization' header is missing the access token."}}
   at AzureExtension.Services.DevBox.DevBoxManagementService.DevBoxHttpRequest(HttpClient client, Uri webUri, IDeveloperId developerId, HttpMethod method, HttpContent requestContent)
   at AzureExtension.Services.DevBox.DevBoxManagementService.HttpsRequestToManagementPlane(Uri webUri, IDeveloperId developerId, HttpMethod method, HttpContent requestContent)
   at AzureExtension.DevBox.DevBoxProvider.GetDevBoxProjectsAsync(IDeveloperId developerId)
   at AzureExtension.DevBox.DevBoxProvider.GetDevBoxesAsync(IDeveloperId developerId)
   at AzureExtension.DevBox.DevBoxProvider.<>c__DisplayClass22_0.<<CreateAdaptiveCardSessionForDeveloperId>b__0>d.MoveNext()`
