### ISSUE TITLE
Report AppInstaller registration / update status to the user in Machine Configuration flow

### ISSUE THREAD

**Issue by adrastogi** [microsoft/devhome#2194]
### Dev Home version

0.1001.389.0

### Windows build number

10.0.19045.3930

### Other software

OS Build Version: 10.0.19045.3930.amd64fre.vb_release.191206-1406
.NET Version: .NET 8.0.1

### Steps to reproduce the bug

1. Set up a new instance of Dev Home
2. Navigate to the machine configuration page

### Expected result

All flows are available to run

### Actual result

A few flows (the Install Applications one is the one I remember, there was at least one other) are grayed out.

From looking at the SetupFlow logs, WinGet wasn't available, so the system registered it, which wasn't sufficient. I *think* if I had navigated back to the page, it would have then checked for updates (which I didn't try, because I went to the Store to manually get updates). Updating was the fix for that behavior. It would be helpful if the page communicated details about the missing registration and missing updates back to the user somehow. 

### Included System Information

CPU: Intel(R) Xeon(R) CPU E5-1650 v2 @ 3.50GHz
Physical Memory: 15.93GB (9.14GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome.Canary_0.1001.389.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension.Canary_0.1000.389.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeAzureExtension.Canary_0.500.383.0_x64__8wekyb3d8bbwe

Widget Service: 
Microsoft.WidgetsPlatformRuntime_1.1.0.0_x64__8wekyb3d8bbwe

**Comment by adrastogi** [comment]
Relevant excerpt from Setup Flow log:

```
[2024/01/29 10:29:50.1363][AppManagement] INFO: Initializing AppManagementInitializer
[2024/01/29 10:29:50.3733][AppManagement] INFO: Initialize catalogs from all data sources
[2024/01/29 10:29:50.3738][AppManagement] INFO: Initializing package list from data source WinGetPackageRestoreDataSource
[2024/01/29 10:29:50.3859][AppManagement] WARN: Restore data source skipped with status: Error
[2024/01/29 10:29:50.3860][AppManagement] INFO: Initializing package list from data source WinGetPackageJsonDataSource
[2024/01/29 10:29:50.3863][AppManagement] INFO: Reading package list from JSON file C:\Program Files\WindowsApps\Microsoft.Windows.DevHome.Canary_0.1001.389.0_x64__8wekyb3d8bbwe\DevHome.SetupFlow/Assets/AppManagementPackages.json
[2024/01/29 10:29:50.4320][AppManagement] INFO: Initializing package list from data source WinGetFeaturedApplicationsDataSource
[2024/01/29 10:29:51.1382][AppManagement] INFO: Initializing featured applications from all extensions
[2024/01/29 10:29:51.1385][AppManagement] INFO: Ensuring AppInstaller is registered ...
[2024/01/29 10:29:51.1391][AppManagement] INFO: Attempting to create a dummy out-of-proc PackageManager COM object to test if the COM server is available
[2024/01/29 10:29:51.1469][AppManagement] ERROR: Failed to create dummy PackageManager COM object. WinGet COM Server is not available.
System.Runtime.InteropServices.COMException (0x80040154): Class not registered

   at DevHome.SetupFlow.Common.WindowsPackageManager.WindowsPackageManagerDefaultFactory.CreateInstance[T](Guid clsid, Guid iid)
   at DevHome.SetupFlow.Common.WindowsPackageManager.WindowsPackageManagerFactory.CreateInstance[T]()
   at DevHome.SetupFlow.Services.WindowsPackageManager.<IsCOMServerAvailableAsync>b__31_0()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at DevHome.SetupFlow.Services.WindowsPackageManager.IsCOMServerAvailableAsync()
[2024/01/29 10:29:52.0454][AppManagement] INFO: WinGet COM Server is not available. AppInstaller might be staged but not registered, attempting to register it to fix the issue
[2024/01/29 10:29:52.0455][AppManagement] INFO: Starting AppInstaller registration ...
[2024/01/29 10:30:00.5544][AppManagement] INFO: AppInstaller registered successfully
[2024/01/29 10:30:00.5546][AppManagement] INFO: Attempting to create a dummy out-of-proc PackageManager COM object to test if the COM server is available
[2024/01/29 10:30:00.5579][AppManagement] ERROR: Failed to create dummy PackageManager COM object. WinGet COM Server is not available.
System.Runtime.InteropServices.COMException (0x80040154): Class not registered

   at DevHome.SetupFlow.Common.WindowsPackageManager.WindowsPackageManagerDefaultFactory.CreateInstance[T](Guid clsid, Guid iid)
   at DevHome.SetupFlow.Common.WindowsPackageManager.WindowsPackageManagerFactory.CreateInstance[T]()
   at DevHome.SetupFlow.Services.WindowsPackageManager.<IsCOMServerAvailableAsync>b__31_0()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at DevHome.SetupFlow.Services.WindowsPackageManager.IsCOMServerAvailableAsync()
[2024/01/29 10:30:00.5582][AppManagement] ERROR: WinGet COM Server is not available after AppInstaller registration
[2024/01/29 10:30:00.5583][AppManagement] INFO: Completed AppManagementInitializer initialization
[2024/01/29 10:31:39.8351][SetupFlow] ERROR: Unable to query for Dev Drive enablement: Unable to find an entry point named 'GetDeveloperDriveEnablementState' in DLL 'api-ms-win-core-sysinfo-l1-2-6.dll'.
[2024/01/29 10:33:46.8767][SetupFlow] ERROR: Unable to query for Dev Drive enablement: Unable to find an entry point named 'GetDeveloperDriveEnablementState' in DLL 'api-ms-win-core-sysinfo-l1-2-6.dll'.
[2024/01/29 10:33:48.7480][SetupFlow] ERROR: Unable to query for Dev Drive enablement: Unable to find an entry point named 'GetDeveloperDriveEnablementState' in DLL 'api-ms-win-core-sysinfo-l1-2-6.dll'.
[2024/01/29 10:33:48.7484][Orchestrator] INFO: Moving to MainPageViewModel
[2024/01/29 10:33:48.7485][Orchestrator] INFO: Executing post-navigation tasks for page MainPageViewModel
[2024/01/29 10:33:48.7487][AppManagement] INFO: Attempting to create a dummy out-of-proc PackageManager COM object to test if the COM server is available
[2024/01/29 10:33:48.7630][AppManagement] ERROR: Failed to create dummy PackageManager COM object. WinGet COM Server is not available.
System.Runtime.InteropServices.COMException (0x80040154): Class not registered

   at DevHome.SetupFlow.Common.WindowsPackageManager.WindowsPackageManagerDefaultFactory.CreateInstance[T](Guid clsid, Guid iid)
   at DevHome.SetupFlow.Common.WindowsPackageManager.WindowsPackageManagerFactory.CreateInstance[T]()
   at DevHome.SetupFlow.Services.WindowsPackageManager.<IsCOMServerAvailableAsync>b__31_0()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at DevHome.SetupFlow.Services.WindowsPackageManager.IsCOMServerAvailableAsync()
[2024/01/29 10:33:48.7635][SetupFlow] WARN: WindowsPackageManager COM Server is not available. Package install item is hidden.

```

**Comment by AmelBawa-msft** [comment]
@adrastogi thank you for opening this issue. I love this idea. I did suggested a feature that would potentially allow Dev Home to communicate all the tasks it does in the background including registering App installer, checking for update, recovering from crashes, etc... by implementing an in-app notification system. 

Consider 👍 the referenced issue, or re-activate this one if you have alternative suggestions 🙂
