### ISSUE TITLE
No valid Quickstart extensions being detected on latest Dev Home / Azure Extension combination

### ISSUE THREAD

**Issue by adrastogi** [microsoft/devhome#2935]
### Dev Home version

0.1401.501.0

### Windows build number

10.0.26220.5000

### Other software

OS Build Version: 10.0.26220.5000.amd64fre.ge_current_directadept.240514-1700
.NET Version: .NET 8.0.4

### Steps to reproduce the bug

On a system with the Dev Home Azure extension already installed: 

1. Launch Dev Home and navigate to the Quickstart Playground page in the Machine Configuration page

### Expected result

Dev Home should detect that there is a valid Quickstart extension provider available via the Azure extension package

### Actual result

The feature says that no extension providers are installed. The logs have the error text below:

[2024/05/16 09:32:31.635 ERR] (QuickStartProjectService) Failed to get IQuickStartProjectProvider provider from 'Microsoft.Windows.DevHomeAzureExtension.Canary_0.900.501.0_x64__8wekyb3d8bbwe'
System.InvalidCastException: Specified cast is not valid.
   at WinRT.IObjectReference.As[T](Guid iid)
   at WinRT.IObjectReference.As[T]()
   at System.Collections.Generic.IListImpl`1.Make_IListObjRef()
   at System.Collections.Generic.IListImpl`1.get_Count()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at DevHome.SetupFlow.Services.QuickStartProjectService.GetQuickStartProjectProvidersAsync()
[2024/05/16 09:32:31.642 INF] (QuickstartPlaygroundViewModel) No installed Quickstart providers detected

### Included System Information

CPU: AMD Ryzen Threadripper PRO 3945WX 12-Cores     
Physical Memory: 63.86GB (44.57GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome.Dev_0.1301.480.0_x64__8wekyb3d8bbwe (Core Widget Extension)
Microsoft.Windows.DevHome.Dev_0.1301.480.0_x64__8wekyb3d8bbwe (Hyper-V Extension)
Microsoft.Windows.DevHomeAzureExtension.Dev_0.800.480.0_x64__8wekyb3d8bbwe (Dev Home Azure Extension (Dev))
9932MartCliment.WingetUIWidgets_0.5.0.0_x64__g91dtg5srk15g (WingetUI Widgets (Preview))
Microsoft.Windows.DevHomeGitHubExtension.Canary_0.1400.500.0_x64__8wekyb3d8bbwe (Dev Home GitHub Extension (Canary))
Microsoft.Windows.DevHomeAzureExtension.Canary_0.900.501.0_x64__8wekyb3d8bbwe (Dev Home Azure Extension (Canary))
Microsoft.Windows.DevHome.Canary_0.1401.501.0_x64__8wekyb3d8bbwe (Core Widget Extension)
Microsoft.Windows.DevHome.Canary_0.1401.501.0_x64__8wekyb3d8bbwe (Hyper-V Extension)

Widget Service: 
MicrosoftWindows.Client.WebExperience_524.13200.0.0_x64__cw5n1h2txyewy

**Comment by adrastogi** [comment]
False alarm- the kicker was the dev versions being also installed, related to #2451 

(h/t to @jaholme for the psychic debugging)
