### ISSUE TITLE
"We're having trouble displaying widgets. Restarting Dev Home may help." error when launching Dev Home on Windows 10

### ISSUE THREAD

**Issue by adrastogi** [microsoft/devhome#2945]
### Dev Home version

0.1401.501.0

### Windows build number

10.0.19045.4412

### Other software

OS Build Version: 10.0.19045.4412.amd64fre.vb_release.191206-1406
.NET Version: .NET 8.0.4

### Steps to reproduce the bug

On the latest Dev Home build, launch Dev Home and observe the dashboard

### Expected result

I'd expect to see some system widgets pinned there along with any other widgets I had previously pinned. 

### Actual result

Dev Home isn't showing any widgets and displays an error message that reads, "We're having trouble displaying widgets. Restarting Dev Home may help.". The error is persistent, though.

### Included System Information

CPU: Intel(R) Xeon(R) CPU E5-1650 v2 @ 3.50GHz
Physical Memory: 15.93GB (10.79GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHomeGitHubExtension.Canary_0.1400.500.0_x64__8wekyb3d8bbwe (Dev Home GitHub Extension (Canary))
Microsoft.Windows.DevHomeAzureExtension.Canary_0.900.501.0_x64__8wekyb3d8bbwe (Dev Home Azure Extension (Canary))
Microsoft.Windows.DevHome.Canary_0.1401.501.0_x64__8wekyb3d8bbwe (Core Widget Extension)
Microsoft.Windows.DevHome.Canary_0.1401.501.0_x64__8wekyb3d8bbwe (Hyper-V Extension)

Widget Service: 
Microsoft.WidgetsPlatformRuntime_1.2.0.0_x64__8wekyb3d8bbwe

**Comment by adrastogi** [comment]
The logs have this interesting snippet.

```
[2024/05/16 11:23:51.447 ERR] (WidgetHostingService) Exception in GetWidgetDefinitionAsync:
System.UnauthorizedAccessException: Access is denied.

Access is denied.

   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Microsoft.Windows.Widgets.Hosts.IWidgetCatalogStaticsMethods.GetDefault(IObjectReference _obj)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at DevHome.Dashboard.Services.WidgetHostingService.GetWidgetCatalogAsync()
[2024/05/16 11:23:51.545 ERR] (WidgetHostingService) Exception in GetWidgetDefinitionAsync:
System.UnauthorizedAccessException: Access is denied.
```

**Comment by BillEisenman** [comment]
I am having problems displaying the Dev Home Dashboard. All of the displayed widgets for CPU, GPU, etc on Windows 11 23H2. The Error Displayed is The type initializer for 'CoreWidgetProvider.Helpers.SystemData' threw an exception. I have tried the restart,,
repair, and uninstall / reinstall methods currently, with no luck. Any ideas as to how to fix this?

**Comment by krschau** [comment]
@BillEisenman Can you share the information included in "Included Extensions Information" above? The easy way to get this is open Dev Home and go to Settings -> Feedback -> Report a bug and copy the text under "Include installed Dev Home extensions and related packages"

**Comment by BillEisenman** [comment]
Included Extensions Information
Extensions:
Microsoft.DevHomeMicrosoftGameDevExtension_0.400.456.0_x64__8wekyb3d8bbwe (Dev Home Microsoft Game Dev Extension (Preview))
9932MartCliment.WingetUIWidgets_0.6.1.0_x64__g91dtg5srk15g (Widgets for UniGetUI (formerly WingetUI))
Microsoft.Windows.DevHomeGitHubExtension_0.1500.533.0_x64__8wekyb3d8bbwe (Dev Home GitHub Extension (Preview))
Microsoft.Windows.DevHomeAzureExtension_0.1000.533.0_x64__8wekyb3d8bbwe (Dev Home Azure Extension (Preview))
Microsoft.Windows.DevHome_0.1501.533.0_x64__8wekyb3d8bbwe (Core Widget Extension)
Microsoft.Windows.DevHome_0.1501.533.0_x64__8wekyb3d8bbwe (Hyper-V Extension)

Widget Service:
MicrosoftWindows.Client.WebExperience_524.13200.0.0_x64__cw5n1h2txyewy

**Comment by BillEisenman** [comment]
For a little more information, the problem still occurs under 0.1501.533.0 which was installed from the Microsoft Store after complete install.

**Comment by realsircodesalot** [comment]
Just ran into this issue myself after upgrading to Windows 11 - I had DevHome (Preview) installed while still using Windows 10.  I receive the same error as shown in the picture for #2673.  It seems there are several duplicates of this issue, I'm hoping I picked the correct one to comment on.  

Is there any status update on this?  Anyone find any workarounds?

**Comment by krschau** [comment]
@realsircodesalot There's a new issue we've been seeing that results in this error message being shown, and I suspect (but am not sure) it's what you're seeing. We're actively trying to collect data on when it happens. If you could check, I'd love to know what version(s) of the widget service you have -- this can be found in Dev Home under Settings -> Feedback -> Report a bug -> "Include installed Dev Home extensions and related packages" under the "Widget Service:" heading.

A workaround for this particular error is to go to the Windows Widget Board (keyboard shortcut: win+w) and click the + button to add a widget. You don't actually have to add one, but bringing up the dialog gets things started such that Dev Home should be back to normal.

**Comment by realsircodesalot** [comment]
Wow, didn't know about the win+w shortcut!  I added those widgets there and received the same exception error message.

Here's the info from the Feedback:

---

**Dev Home Version**
0.1701.597.0

**Windows build number**
10.0.22631.4037

**Other software**
OS Build Version: 10.0.22631.4037.amd64fre.ni_release.220506-1250
.NET Version: .NET 8.0.7

**Included System Information**
CPU: 12th Gen Intel(R) Core(TM) i7-1265U
Physical Memory: 31.2GB (6.75GB free)
Processor Architecture: x64

**Included Extensions Information**
Extensions: 
Microsoft.Windows.DevHome_0.1701.597.0_x64__8wekyb3d8bbwe (Core Widget Extension)
Microsoft.Windows.DevHome_0.1701.597.0_x64__8wekyb3d8bbwe (Hyper-V Extension)
Microsoft.Windows.DevHome_0.1701.597.0_x64__8wekyb3d8bbwe (Windows Subsystem for Linux Extension)
Microsoft.Windows.DevHome_0.1701.597.0_x64__8wekyb3d8bbwe (Git)
Microsoft.Windows.DevHomeGitHubExtension_0.1700.597.0_x64__8wekyb3d8bbwe (Dev Home GitHub Extension (Preview))
Microsoft.Windows.DevHomeAzureExtension_0.1200.597.0_x64__8wekyb3d8bbwe (Dev Home Azure Extension (Preview))

Widget Service: 
MicrosoftWindows.Client.WebExperience_524.18500.10.0_x64__cw5n1h2txyewy

**Comment by hgohel** [comment]
@krschau The workaround you suggested, i.e. Win+W, press + key (but don't add any widget). Now DevHome loads all my widgets. Thank you!

For reference, here's my config when I was having the problem for your investigation:

DevHome version: 0.1701.597.0
Windows Build Number: 10.0.22631.4037
Other software: OS Build Version: 10.0.22631.4037.amd64fre.ni_release.220506-1250
.NET Version: .NET 8.0.7
Included Extensions Information:
Extensions: 
Microsoft.Windows.DevHome_0.1701.597.0_x64__8wekyb3d8bbwe (Core Widget Extension)
Microsoft.Windows.DevHome_0.1701.597.0_x64__8wekyb3d8bbwe (Hyper-V Extension)
Microsoft.Windows.DevHome_0.1701.597.0_x64__8wekyb3d8bbwe (Windows Subsystem for Linux Extension)
Microsoft.Windows.DevHome_0.1701.597.0_x64__8wekyb3d8bbwe (Git)
Microsoft.Windows.DevHomeGitHubExtension_0.1700.597.0_x64__8wekyb3d8bbwe (Dev Home GitHub Extension (Preview))

Widget Service: 
MicrosoftWindows.Client.WebExperience_524.23700.10.0_x64__cw5n1h2txyewy

**Comment by Wraiyth** [comment]
I am having the same issue.

Extensions: 
Microsoft.Windows.DevHome_0.1701.597.0_x64__8wekyb3d8bbwe (Core Widget Extension)
Microsoft.Windows.DevHome_0.1701.597.0_x64__8wekyb3d8bbwe (Hyper-V Extension)
Microsoft.Windows.DevHome_0.1701.597.0_x64__8wekyb3d8bbwe (Windows Subsystem for Linux Extension)
Microsoft.Windows.DevHome_0.1701.597.0_x64__8wekyb3d8bbwe (Git)
Microsoft.Windows.DevHomeGitHubExtension_0.1700.597.0_x64__8wekyb3d8bbwe (Dev Home GitHub Extension (Preview))
Microsoft.Windows.DevHomeAzureExtension_0.1200.597.0_x64__8wekyb3d8bbwe (Dev Home Azure Extension (Preview))

Widget Service: 
MicrosoftWindows.Client.WebExperience_524.23700.10.0_x64__cw5n1h2txyewy
Microsoft.WidgetsPlatformRuntime_1.4.0.0_x64__8wekyb3d8bbwe

**Comment by krschau** [comment]
@hgohel and @Wraiyth If it's not too much trouble, could you share your logs? I'll have the bot give instructions but if you don't want to share everything, it would be useful just to see the .dhlog file under logs/DevHome from a day you saw/are seeing this issue.
/logs

**Comment by hgohel** [comment]
> could you share your logs? ... it would be useful just to see the .dhlog file under logs/DevHome from a day you saw/are seeing this issue.

Here's my log file from a day on which it wasn't working, after which I used your workaround, and the log shows no errors after that: [My .dhlog file](https://1drv.ms/u/s!AlDdZIUGh4l1jsVkZqR7UIVtdxaR4A?e=Atmfen) link expires in a few days, I can re-up it if needed.

**Comment by mgreenegit** [comment]
+1 on this issue

**Comment by lorette-m** [comment]
Sorry, but where is working solution? win + w didn't work for me
