### ISSUE TITLE
.NET PowerShell runspace not auto-loading the Hyper-V Module when Hyper-V is enabled

### ISSUE THREAD

**Issue by bbonaby** [microsoft/devhome#2955]
### Steps to reproduce the bug

The Hyper-V extension requires that the Hyper-V PowerShell module be loaded into the PowerShell runspace before attempting to perform any Hyper-V functionality. If it is not loaded attempting to perform any operation will return an error.

When the Hyper-V PowerShell windows feature is enabled, it will be loaded into a users PowerShell runspace by default. However, for some machines it is not getting loaded into the runspace resulting in a similar error as below (Note: the below error occured when navigating to the environment page for the first time after launching Dev Home):

`System.Management.Automation.CommandNotFoundException: The 'Get-VM' command was found in the module 'Hyper-V', but the module could not be loaded. For more information, run 'Import-Module Hyper-V'.`
   at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
   at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
   at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
   at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.Invoke(IEnumerable input, PSInvocationSettings settings)
   at HyperVExtension.Services.PowerShellService.ExecuteIndividualStatements(IEnumerable`1 commandLineStatements, PipeType pipeType)
   at HyperVExtension.Services.PowerShellService.Execute(IEnumerable`1 commandLineStatements, PipeType pipeType)

Another Note: Attempting to import the module has no affect, and the error persists after testing this. So, the error messaging is misleading

In the past I noticed this issue and added a workaround where we use the `Get-Module -ListAvailable` command as a way to force the the Hyper-V module to be loaded into the runspace, however this negatively affect perf. After reimaging my machine and enabling Hyper-V this error went away, so we removed the workaround. However, we have received at least one report for another user that they are encountering this error.

There are two things we can attempt to do to fix this:

1. Re-add the work around that we know will work on most if not all PCs
2. Find a different work around that does not negatively impact the perf of loading the Hyper-V VMs

### Expected result

Hyper-V VMs load without errors

### Actual result

Hyper-V VMs do not load and the user recieves the following error after navigating to the environments page without doing anything:
![image](https://github.com/microsoft/devhome/assets/105318831/6b5b31e7-38bf-4270-a929-f4eb1c127742)

**Comment by wn0x00** [comment]
how to do it
