### ISSUE TITLE
Adaptive card flow for QuickStart Playground doesn't appear to be displaying error states?

### ISSUE THREAD

**Issue by adrastogi** [microsoft/devhome#2964]
### Dev Home version

0.1401.501.0

### Windows build number

10.0.22631.3593

### Other software

OS Build Version: 10.0.22631.3593.amd64fre.ni_release.220506-1250
.NET Version: .NET 8.0.4

### Steps to reproduce the bug

I was trying to manually simulate some errors in the Azure extension where I had the dependency UI controller generate an exception that I expected the Quickstart feature code to handle. 

### Expected result

I _think_ we should be showing the propagated exception data as an adaptive card? (I need to look closer at the implementation to confirm.)

### Actual result

There doesn't appear to be any information provided back to the user about the exception. 

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.1301.477.0_x64__8wekyb3d8bbwe (Dev Home (Preview))
Microsoft.Windows.DevHome_0.1301.477.0_x64__8wekyb3d8bbwe (Dev Home (Preview))
Microsoft.Windows.DevHomeGitHubExtension_0.1300.477.0_x64__8wekyb3d8bbwe (Dev Home GitHub Extension (Preview))
Microsoft.Windows.DevHomeGitHubExtension.Canary_0.1400.500.0_x64__8wekyb3d8bbwe (Dev Home GitHub Extension (Canary))
Microsoft.Windows.DevHome.Canary_0.1401.501.0_x64__8wekyb3d8bbwe (Core Widget Extension)
Microsoft.Windows.DevHome.Canary_0.1401.501.0_x64__8wekyb3d8bbwe (Hyper-V Extension)
Microsoft.Windows.DevHomeAzureExtension.Canary_0.900.501.0_x64__8wekyb3d8bbwe (Dev Home Azure Extension (Canary))
Microsoft.Windows.DevHomeAzureExtension.Dev_0.0.0.0_x64__8wekyb3d8bbwe (Dev Home Azure Extension (Dev))
Microsoft.Windows.DevHome.Dev_0.0.0.0_x64__8wekyb3d8bbwe (Core Widget Extension)
Microsoft.Windows.DevHome.Dev_0.0.0.0_x64__8wekyb3d8bbwe (Hyper-V Extension)

Widget Service: 
MicrosoftWindows.Client.WebExperience_524.12200.10.0_x64__cw5n1h2txyewy

**Comment by adrastogi** [comment]
There are a few things going on here:
- If the QuickstartAdaptiveCardResult corresponds to a failure, we currently bail out without showing anything, so we should consider what we'd want to report here
- The result has limited information in it, which relates back to the exception Dev Home receives (e.g., `Message` is an empty string)

![Image](https://github.com/microsoft/devhome/assets/8368026/0c4c93e9-aa49-41bf-9454-b021c4eeb251)

```
[22:29:52 ERR] CreateAdaptiveCardSessionForExtensionInitialization for: QuickStartProject provider: Dev Container using OpenAI failed due to exception
System.Runtime.InteropServices.COMException (0x80131620)
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Microsoft.Windows.DevHome.SDK.IQuickStartProjectProviderMethods.CreateAdaptiveCardSessionForExtensionInitialization(IObjectReference _obj)
   at ABI.Microsoft.Windows.DevHome.SDK.IQuickStartProjectProvider.global::Microsoft.Windows.DevHome.SDK.IQuickStartProjectProvider.CreateAdaptiveCardSessionForExtensionInitialization()
   at DevHome.SetupFlow.Models.QuickStartProjectProvider.CreateAdaptiveCardSessionForExtensionInitialization()
```
