### ISSUE TITLE
DevDiagnostics: selecting multiple tools to unregister causes DD to crash

### ISSUE THREAD

**Issue by andreww-msft** [microsoft/devhome#3826]
### Steps to reproduce the bug

1. Register 4-5 tools, doesn't matter what they are.
2. In Settings, expand the "Edit or unregister existing tools" list.
3. Select 4-5 tools.
4. Click Unregister.
5. See DD crashes.

Note: selecting just 3 tools to unregister works OK, but 4-5 or more causes the crash.

**Comment by timkur** [comment]
{"Index must be greater than or equal to 0 and less than 1. (Parameter 'index')"}

   at CommunityToolkit.WinUI.UI.Controls.DataGridSelectedItemsCollection.get_Item(Int32 index)
   at DevHome.DevDiagnostics.Controls.EditToolsControl.UnregisterToolButton_Click(Object sender, RoutedEventArgs e) in F:\DevHome\tools\DevDiagnostics\DevHome.DevDiagnostics\Controls\EditToolsControl.xaml.cs:line 27
   at WinRT._EventSource_global__Microsoft_UI_Xaml_RoutedEventHandler.EventState.<GetEventInvoke>b__1_0(Object sender, RoutedEventArgs e) in C:\__w\1\s\BuildOutput\obj\x86fre\src\projection\generated\WinRTEventHelpers.cs:line 8294
   at ABI.Microsoft.UI.Xaml.RoutedEventHandler.Do_Abi_Invoke(IntPtr thisPtr, IntPtr sender, IntPtr e) in C:\__w\1\s\BuildOutput\obj\x86fre\src\projection\generated\Microsoft.UI.Xaml.cs:line 26265
